# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from orchestrator.v1 import tasks_pb2 as orchestrator_dot_v1_dot_tasks__pb2


class TaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/orchestrator.v1.TaskService/CreateTask',
                request_serializer=orchestrator_dot_v1_dot_tasks__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=orchestrator_dot_v1_dot_tasks__pb2.CreateTaskResponse.FromString,
                )
        self.ListTasks = channel.unary_unary(
                '/orchestrator.v1.TaskService/ListTasks',
                request_serializer=orchestrator_dot_v1_dot_tasks__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=orchestrator_dot_v1_dot_tasks__pb2.ListTasksResponse.FromString,
                )
        self.GetTask = channel.unary_unary(
                '/orchestrator.v1.TaskService/GetTask',
                request_serializer=orchestrator_dot_v1_dot_tasks__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=orchestrator_dot_v1_dot_tasks__pb2.GetTaskResponse.FromString,
                )
        self.TriggerTestTask = channel.unary_unary(
                '/orchestrator.v1.TaskService/TriggerTestTask',
                request_serializer=orchestrator_dot_v1_dot_tasks__pb2.TriggerTestTaskRequest.SerializeToString,
                response_deserializer=orchestrator_dot_v1_dot_tasks__pb2.TriggerTestTaskResponse.FromString,
                )


class TaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerTestTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=orchestrator_dot_v1_dot_tasks__pb2.CreateTaskRequest.FromString,
                    response_serializer=orchestrator_dot_v1_dot_tasks__pb2.CreateTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=orchestrator_dot_v1_dot_tasks__pb2.ListTasksRequest.FromString,
                    response_serializer=orchestrator_dot_v1_dot_tasks__pb2.ListTasksResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=orchestrator_dot_v1_dot_tasks__pb2.GetTaskRequest.FromString,
                    response_serializer=orchestrator_dot_v1_dot_tasks__pb2.GetTaskResponse.SerializeToString,
            ),
            'TriggerTestTask': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerTestTask,
                    request_deserializer=orchestrator_dot_v1_dot_tasks__pb2.TriggerTestTaskRequest.FromString,
                    response_serializer=orchestrator_dot_v1_dot_tasks__pb2.TriggerTestTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.v1.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.v1.TaskService/CreateTask',
            orchestrator_dot_v1_dot_tasks__pb2.CreateTaskRequest.SerializeToString,
            orchestrator_dot_v1_dot_tasks__pb2.CreateTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.v1.TaskService/ListTasks',
            orchestrator_dot_v1_dot_tasks__pb2.ListTasksRequest.SerializeToString,
            orchestrator_dot_v1_dot_tasks__pb2.ListTasksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.v1.TaskService/GetTask',
            orchestrator_dot_v1_dot_tasks__pb2.GetTaskRequest.SerializeToString,
            orchestrator_dot_v1_dot_tasks__pb2.GetTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TriggerTestTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orchestrator.v1.TaskService/TriggerTestTask',
            orchestrator_dot_v1_dot_tasks__pb2.TriggerTestTaskRequest.SerializeToString,
            orchestrator_dot_v1_dot_tasks__pb2.TriggerTestTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
